"""Add title field to documents

Revision ID: 3471ff32312b
Revises: b4ee40e6bedb
Create Date: 2025-07-07 21:26:34.175391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3471ff32312b'
down_revision: Union[str, Sequence[str], None] = 'b4ee40e6bedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'title')
    # ### end Alembic commands ###
